apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: kafka
spec:
  project: default
  source:
    repoURL: https://github.com/harvest7777/webhook
    targetRevision: HEAD
    path: manifests/app-manifests/kafka
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
